apiVersion: v1
kind: Service
metadata:
  name: eks-devops-demo
  namespace: devops-demo
  labels:
    app: eks-devops-demo
spec:
  type: LoadBalancer
  selector:
    app: eks-devops-demo
  ports:
    - name: http
      port: 80
      targetPort: http
