apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eks-devops-demo
  namespace: devops-demo
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: eks-devops-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
